// Code generated by protoc-gen-go. DO NOT EDIT.
// source: petstorebidi.proto

package bidiproxygw

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Timestamp1           int64    `protobuf:"varint,1,opt,name=timestamp1,proto3" json:"timestamp1,omitempty"`
	Timestamp2           int64    `protobuf:"varint,2,opt,name=timestamp2,proto3" json:"timestamp2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f1b2fe03564763, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetTimestamp1() int64 {
	if m != nil {
		return m.Timestamp1
	}
	return 0
}

func (m *User) GetTimestamp2() int64 {
	if m != nil {
		return m.Timestamp2
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "bidiproxygw.User")
}

func init() { proto.RegisterFile("petstorebidi.proto", fileDescriptor_c4f1b2fe03564763) }

var fileDescriptor_c4f1b2fe03564763 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x48, 0x2d, 0x29,
	0x2e, 0xc9, 0x2f, 0x4a, 0x4d, 0xca, 0x4c, 0xc9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x06, 0xb1, 0x0b, 0x8a, 0xf2, 0x2b, 0x2a, 0xd3, 0xcb, 0x95, 0xdc, 0xb8, 0x58, 0x42, 0x8b, 0x53,
	0x8b, 0x84, 0xe4, 0xb8, 0xb8, 0x4a, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x0c, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x90, 0x44, 0x50, 0xe4, 0x8d, 0x24, 0x98, 0xd0, 0xe4, 0x8d,
	0x8c, 0x7c, 0xb8, 0x84, 0x03, 0x52, 0x4b, 0x82, 0x41, 0x56, 0x05, 0xa7, 0x16, 0x95, 0x65, 0x26,
	0xa7, 0x3a, 0x65, 0xa6, 0x64, 0x0a, 0x99, 0x72, 0x71, 0x3a, 0x95, 0xe6, 0x64, 0x83, 0xac, 0x28,
	0x16, 0x12, 0xd4, 0x43, 0xb2, 0x59, 0x0f, 0x24, 0x26, 0x85, 0x29, 0xa4, 0xc1, 0x68, 0xc0, 0x98,
	0xc4, 0x06, 0x76, 0xa9, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xf7, 0xc8, 0xd4, 0xbf, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PetStoreServiceBidiClient is the client API for PetStoreServiceBidi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PetStoreServiceBidiClient interface {
	BulkUsers(ctx context.Context, opts ...grpc.CallOption) (PetStoreServiceBidi_BulkUsersClient, error)
}

type petStoreServiceBidiClient struct {
	cc *grpc.ClientConn
}

func NewPetStoreServiceBidiClient(cc *grpc.ClientConn) PetStoreServiceBidiClient {
	return &petStoreServiceBidiClient{cc}
}

func (c *petStoreServiceBidiClient) BulkUsers(ctx context.Context, opts ...grpc.CallOption) (PetStoreServiceBidi_BulkUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PetStoreServiceBidi_serviceDesc.Streams[0], "/bidiproxygw.PetStoreServiceBidi/BulkUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &petStoreServiceBidiBulkUsersClient{stream}
	return x, nil
}

type PetStoreServiceBidi_BulkUsersClient interface {
	Send(*User) error
	Recv() (*User, error)
	grpc.ClientStream
}

type petStoreServiceBidiBulkUsersClient struct {
	grpc.ClientStream
}

func (x *petStoreServiceBidiBulkUsersClient) Send(m *User) error {
	return x.ClientStream.SendMsg(m)
}

func (x *petStoreServiceBidiBulkUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PetStoreServiceBidiServer is the server API for PetStoreServiceBidi service.
type PetStoreServiceBidiServer interface {
	BulkUsers(PetStoreServiceBidi_BulkUsersServer) error
}

func RegisterPetStoreServiceBidiServer(s *grpc.Server, srv PetStoreServiceBidiServer) {
	s.RegisterService(&_PetStoreServiceBidi_serviceDesc, srv)
}

func _PetStoreServiceBidi_BulkUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PetStoreServiceBidiServer).BulkUsers(&petStoreServiceBidiBulkUsersServer{stream})
}

type PetStoreServiceBidi_BulkUsersServer interface {
	Send(*User) error
	Recv() (*User, error)
	grpc.ServerStream
}

type petStoreServiceBidiBulkUsersServer struct {
	grpc.ServerStream
}

func (x *petStoreServiceBidiBulkUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func (x *petStoreServiceBidiBulkUsersServer) Recv() (*User, error) {
	m := new(User)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PetStoreServiceBidi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bidiproxygw.PetStoreServiceBidi",
	HandlerType: (*PetStoreServiceBidiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BulkUsers",
			Handler:       _PetStoreServiceBidi_BulkUsers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "petstorebidi.proto",
}
