// This file registers with grpc service. This file was auto-generated by mashling at
// 2019-05-17 12:26:08.827913713 +0530 IST m=+0.072356403
package bidiproxygw

import (
	
	"log"
	"errors"
	servInfo "github.com/project-flogo/grpc/trigger"
	"google.golang.org/grpc"
)



type serviceImplsamplebidiSampleServiceBidiserver struct {
	trigger *servInfo.Trigger
	serviceInfo *servInfo.ServiceInfo
}

var serviceInfosamplebidiSampleServiceBidiserver = &servInfo.ServiceInfo{
	ProtoName: "samplebidi",
	ServiceName: "SampleServiceBidi",
}

func init() {
	servInfo.ServiceRegistery.RegisterServerService(&serviceImplsamplebidiSampleServiceBidiserver{serviceInfo: serviceInfosamplebidiSampleServiceBidiserver})
}

// RunRegisterServerService registers server method implimentaion with grpc
func (s *serviceImplsamplebidiSampleServiceBidiserver) RunRegisterServerService(serv *grpc.Server, trigger *servInfo.Trigger) {
	service := &serviceImplsamplebidiSampleServiceBidiserver{
		trigger: trigger,
		serviceInfo: serviceInfosamplebidiSampleServiceBidiserver,
	}
	RegisterSampleServiceBidiServer(serv, service)
}

func (s *serviceImplsamplebidiSampleServiceBidiserver) BidiStreaming(bdReq SampleServiceBidi_BidiStreamingServer) error {

	methodName := "BidiStreaming"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["strmReq"] = bdReq

	_, data, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
		return err
	}

	if data != nil && data.(map[string]interface{})["error"] != nil {
		log.Println("error from end server: ", data.(map[string]interface{})["error"])
		return errors.New(data.(map[string]interface{})["error"].(string))
	}
	return nil
}

func (s *serviceImplsamplebidiSampleServiceBidiserver) ServiceInfo() *servInfo.ServiceInfo {
	return s.serviceInfo
}

