// This file registers with grpc service. This file was auto-generated by mashling at
// 2018-12-12 16:03:56.262412907 -0700 MST m=+0.025831704
package rest2grpc

import (
	
	"encoding/json"
	"fmt"
	"strings"
	"golang.org/x/net/context"
	
	"log"
	"errors"
	servInfo "github.com/project-flogo/grpc/trigger"
	"google.golang.org/grpc"
)



type serviceImplpetstoreRest2GRPCPetStoreServiceserver struct {
	trigger *servInfo.Trigger
	serviceInfo *servInfo.ServiceInfo
}

var serviceInfopetstoreRest2GRPCPetStoreServiceserver = &servInfo.ServiceInfo{
	ProtoName: "petstore",
	ServiceName: "Rest2GRPCPetStoreService",
}

func init() {
	servInfo.ServiceRegistery.RegisterServerService(&serviceImplpetstoreRest2GRPCPetStoreServiceserver{serviceInfo: serviceInfopetstoreRest2GRPCPetStoreServiceserver})
}

// RunRegisterServerService registers server method implimentaion with grpc
func (s *serviceImplpetstoreRest2GRPCPetStoreServiceserver) RunRegisterServerService(serv *grpc.Server, trigger *servInfo.Trigger) {
	service := &serviceImplpetstoreRest2GRPCPetStoreServiceserver{
		trigger: trigger,
		serviceInfo: serviceInfopetstoreRest2GRPCPetStoreServiceserver,
	}
	RegisterRest2GRPCPetStoreServiceServer(serv, service)
}

func (s *serviceImplpetstoreRest2GRPCPetStoreServiceserver) PetById(ctx context.Context, req *PetByIdRequest) (res *PetResponse,err error) {

	methodName := "PetById"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["contextdata"] = ctx
	grpcData["reqdata"] = req

	_, replyData, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
	}

	typeHandRes := fmt.Sprintf("%T", replyData)
	if strings.Compare(typeHandRes, "*status.statusError") == 0 {
		return res, replyData.(error)
	}
	typeMethodRes := fmt.Sprintf("%T", res)
	if strings.Compare(typeHandRes, typeMethodRes) == 0 {
		res = replyData.(*PetResponse)
	} else  if replyData != nil {
		var errValue = replyData.(map[string]interface{})["error"]
		if errValue != nil && len(errValue.(string)) != 0 {
			return res, errors.New(errValue.(string))
		} else {
			rDBytes, err := json.Marshal(replyData)
			if err != nil {
				log.Println("error: ", err)
			}

			err = json.Unmarshal(rDBytes, &res)
			if err != nil {
				log.Println("error: ", err)
			}
		}
	} else {
		return nil, errors.New("Exception at gateway end")
	}
	//log.Println("response: ", res)

	//User implimentation area

	return res, err
}

func (s *serviceImplpetstoreRest2GRPCPetStoreServiceserver) UserByName(ctx context.Context, req *UserByNameRequest) (res *UserResponse,err error) {

	methodName := "UserByName"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["contextdata"] = ctx
	grpcData["reqdata"] = req

	_, replyData, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
	}

	typeHandRes := fmt.Sprintf("%T", replyData)
	if strings.Compare(typeHandRes, "*status.statusError") == 0 {
		return res, replyData.(error)
	}
	typeMethodRes := fmt.Sprintf("%T", res)
	if strings.Compare(typeHandRes, typeMethodRes) == 0 {
		res = replyData.(*UserResponse)
	} else  if replyData != nil {
		var errValue = replyData.(map[string]interface{})["error"]
		if errValue != nil && len(errValue.(string)) != 0 {
			return res, errors.New(errValue.(string))
		} else {
			rDBytes, err := json.Marshal(replyData)
			if err != nil {
				log.Println("error: ", err)
			}

			err = json.Unmarshal(rDBytes, &res)
			if err != nil {
				log.Println("error: ", err)
			}
		}
	} else {
		return nil, errors.New("Exception at gateway end")
	}
	//log.Println("response: ", res)

	//User implimentation area

	return res, err
}

func (s *serviceImplpetstoreRest2GRPCPetStoreServiceserver) PetPUT(ctx context.Context, req *PetRequest) (res *PetResponse,err error) {

	methodName := "PetPUT"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["contextdata"] = ctx
	grpcData["reqdata"] = req

	_, replyData, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
	}

	typeHandRes := fmt.Sprintf("%T", replyData)
	if strings.Compare(typeHandRes, "*status.statusError") == 0 {
		return res, replyData.(error)
	}
	typeMethodRes := fmt.Sprintf("%T", res)
	if strings.Compare(typeHandRes, typeMethodRes) == 0 {
		res = replyData.(*PetResponse)
	} else  if replyData != nil {
		var errValue = replyData.(map[string]interface{})["error"]
		if errValue != nil && len(errValue.(string)) != 0 {
			return res, errors.New(errValue.(string))
		} else {
			rDBytes, err := json.Marshal(replyData)
			if err != nil {
				log.Println("error: ", err)
			}

			err = json.Unmarshal(rDBytes, &res)
			if err != nil {
				log.Println("error: ", err)
			}
		}
	} else {
		return nil, errors.New("Exception at gateway end")
	}
	//log.Println("response: ", res)

	//User implimentation area

	return res, err
}

func (s *serviceImplpetstoreRest2GRPCPetStoreServiceserver) UserPUT(ctx context.Context, req *UserRequest) (res *UserResponse,err error) {

	methodName := "UserPUT"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["contextdata"] = ctx
	grpcData["reqdata"] = req

	_, replyData, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
	}

	typeHandRes := fmt.Sprintf("%T", replyData)
	if strings.Compare(typeHandRes, "*status.statusError") == 0 {
		return res, replyData.(error)
	}
	typeMethodRes := fmt.Sprintf("%T", res)
	if strings.Compare(typeHandRes, typeMethodRes) == 0 {
		res = replyData.(*UserResponse)
	} else  if replyData != nil {
		var errValue = replyData.(map[string]interface{})["error"]
		if errValue != nil && len(errValue.(string)) != 0 {
			return res, errors.New(errValue.(string))
		} else {
			rDBytes, err := json.Marshal(replyData)
			if err != nil {
				log.Println("error: ", err)
			}

			err = json.Unmarshal(rDBytes, &res)
			if err != nil {
				log.Println("error: ", err)
			}
		}
	} else {
		return nil, errors.New("Exception at gateway end")
	}
	//log.Println("response: ", res)

	//User implimentation area

	return res, err
}

func (s *serviceImplpetstoreRest2GRPCPetStoreServiceserver) ServiceInfo() *servInfo.ServiceInfo {
	return s.serviceInfo
}

