// This file registers with grpc service. This file was auto-generated by mashling at
	// 2018-12-12 13:02:32.749227615 -0700 MST m=+0.031405704
	package grpc2rest

	import (
		"context"
		
		"encoding/json"
		"github.com/project-flogo/grpc/support"
		
		"errors"
		
		"log"
		

		servInfo "github.com/project-flogo/grpc/activity"
		"google.golang.org/grpc"
	)
	
	
	
	type clientServicepetstoreGRPC2RestPetStoreServiceclient struct {
		serviceInfo *servInfo.ServiceInfo
	}

	var serviceInfopetstoreGRPC2RestPetStoreServiceclient = &servInfo.ServiceInfo{
		ProtoName: "petstore",
		ServiceName: "GRPC2RestPetStoreService",
	}

	func init() {
		servInfo.ClientServiceRegistery.RegisterClientService(&clientServicepetstoreGRPC2RestPetStoreServiceclient{serviceInfo: serviceInfopetstoreGRPC2RestPetStoreServiceclient})
	}

	//GetRegisteredClientService returns client implimentaion stub with grpc connection
	func (cs *clientServicepetstoreGRPC2RestPetStoreServiceclient) GetRegisteredClientService(gCC *grpc.ClientConn) interface{} {
		return NewGRPC2RestPetStoreServiceClient(gCC)
	}

	func (cs *clientServicepetstoreGRPC2RestPetStoreServiceclient) ServiceInfo() *servInfo.ServiceInfo {
		return cs.serviceInfo
	}

	func (cs *clientServicepetstoreGRPC2RestPetStoreServiceclient) InvokeMethod(reqArr map[string]interface{}) map[string]interface{} {

		clientObject := reqArr["ClientObject"].(GRPC2RestPetStoreServiceClient)
		methodName := reqArr["MethodName"].(string)

		switch methodName {
		case "PetById":
			return PetById(clientObject, reqArr)
		case "UserByName":
			return UserByName(clientObject, reqArr)
		case "PetPUT":
			return PetPUT(clientObject, reqArr)
		case "UserPUT":
			return UserPUT(clientObject, reqArr)
		}

		resMap := make(map[string]interface{},2)
		resMap["Response"] = []byte("null")
		resMap["Error"] = errors.New("Method not Available: " + methodName)
		return resMap
	}
	func PetById(client GRPC2RestPetStoreServiceClient, values interface{}) map[string]interface{} {
		req := &PetByIdRequest{}
		support.AssignStructValues(req, values)
		res, err := client.PetById(context.Background(), req)
		b, errMarshl := json.Marshal(res)
		if errMarshl != nil {
			log.Println("Error: ", errMarshl)
			return nil
		}

		resMap := make(map[string]interface{}, 2)
		resMap["Response"] = b
		resMap["Error"] = err
		return resMap
	}
	func UserByName(client GRPC2RestPetStoreServiceClient, values interface{}) map[string]interface{} {
		req := &UserByNameRequest{}
		support.AssignStructValues(req, values)
		res, err := client.UserByName(context.Background(), req)
		b, errMarshl := json.Marshal(res)
		if errMarshl != nil {
			log.Println("Error: ", errMarshl)
			return nil
		}

		resMap := make(map[string]interface{}, 2)
		resMap["Response"] = b
		resMap["Error"] = err
		return resMap
	}
	func PetPUT(client GRPC2RestPetStoreServiceClient, values interface{}) map[string]interface{} {
		req := &PetRequest{}
		support.AssignStructValues(req, values)
		res, err := client.PetPUT(context.Background(), req)
		b, errMarshl := json.Marshal(res)
		if errMarshl != nil {
			log.Println("Error: ", errMarshl)
			return nil
		}

		resMap := make(map[string]interface{}, 2)
		resMap["Response"] = b
		resMap["Error"] = err
		return resMap
	}
	func UserPUT(client GRPC2RestPetStoreServiceClient, values interface{}) map[string]interface{} {
		req := &UserRequest{}
		support.AssignStructValues(req, values)
		res, err := client.UserPUT(context.Background(), req)
		b, errMarshl := json.Marshal(res)
		if errMarshl != nil {
			log.Println("Error: ", errMarshl)
			return nil
		}

		resMap := make(map[string]interface{}, 2)
		resMap["Response"] = b
		resMap["Error"] = err
		return resMap
	}

	