// This file registers with grpc service. This file was auto-generated by mashling at
// 2018-12-05 14:00:51.859472535 -0700 MST m=+0.048388335
package grpc2grpc

import (
	
	"encoding/json"
	"fmt"
	"strings"
	"golang.org/x/net/context"
	
	"log"
	"errors"
	servInfo "github.com/project-flogo/grpc/trigger"
	"google.golang.org/grpc"
)



type serviceImplpetstorePetStoreServiceserver struct {
	trigger *servInfo.Trigger
	serviceInfo *servInfo.ServiceInfo
}

var serviceInfopetstorePetStoreServiceserver = &servInfo.ServiceInfo{
	ProtoName: "petstore",
	ServiceName: "PetStoreService",
}

func init() {
	servInfo.ServiceRegistery.RegisterServerService(&serviceImplpetstorePetStoreServiceserver{serviceInfo: serviceInfopetstorePetStoreServiceserver})
}

// RunRegisterServerService registers server method implimentaion with grpc
func (s *serviceImplpetstorePetStoreServiceserver) RunRegisterServerService(serv *grpc.Server, trigger *servInfo.Trigger) {
	service := &serviceImplpetstorePetStoreServiceserver{
		trigger: trigger,
		serviceInfo: serviceInfopetstorePetStoreServiceserver,
	}
	RegisterPetStoreServiceServer(serv, service)
}

func (s *serviceImplpetstorePetStoreServiceserver) PetById(ctx context.Context, req *PetByIdRequest) (res *PetResponse,err error) {

	methodName := "PetById"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["contextdata"] = ctx
	grpcData["reqdata"] = req

	_, replyData, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
	}

	typeHandRes := fmt.Sprintf("%T", replyData)
	if strings.Compare(typeHandRes, "*status.statusError") == 0 {
		return res, replyData.(error)
	}
	typeMethodRes := fmt.Sprintf("%T", res)
	if strings.Compare(typeHandRes, typeMethodRes) == 0 {
		res = replyData.(*PetResponse)
	} else  if replyData != nil {
		var errValue = replyData.(map[string]interface{})["error"]
		if errValue != nil && len(errValue.(string)) != 0 {
			return res, errors.New(errValue.(string))
		} else {
			rDBytes, err := json.Marshal(replyData)
			if err != nil {
				log.Println("error: ", err)
			}

			err = json.Unmarshal(rDBytes, &res)
			if err != nil {
				log.Println("error: ", err)
			}
		}
	} else {
		return nil, errors.New("Exception at gateway end")
	}
	//log.Println("response: ", res)

	//User implimentation area

	return res, err
}

func (s *serviceImplpetstorePetStoreServiceserver) UserByName(ctx context.Context, req *UserByNameRequest) (res *UserResponse,err error) {

	methodName := "UserByName"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["contextdata"] = ctx
	grpcData["reqdata"] = req

	_, replyData, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
	}

	typeHandRes := fmt.Sprintf("%T", replyData)
	if strings.Compare(typeHandRes, "*status.statusError") == 0 {
		return res, replyData.(error)
	}
	typeMethodRes := fmt.Sprintf("%T", res)
	if strings.Compare(typeHandRes, typeMethodRes) == 0 {
		res = replyData.(*UserResponse)
	} else  if replyData != nil {
		var errValue = replyData.(map[string]interface{})["error"]
		if errValue != nil && len(errValue.(string)) != 0 {
			return res, errors.New(errValue.(string))
		} else {
			rDBytes, err := json.Marshal(replyData)
			if err != nil {
				log.Println("error: ", err)
			}

			err = json.Unmarshal(rDBytes, &res)
			if err != nil {
				log.Println("error: ", err)
			}
		}
	} else {
		return nil, errors.New("Exception at gateway end")
	}
	//log.Println("response: ", res)

	//User implimentation area

	return res, err
}

func (s *serviceImplpetstorePetStoreServiceserver) ListUsers(req *EmptyReq, sReq PetStoreService_ListUsersServer) error {

	methodName := "ListUsers"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["reqdata"] = req
	grpcData["strmReq"] = sReq

	_, data, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
		return err
	}

	if data != nil && data.(map[string]interface{})["error"] != nil {
		log.Println("error from end server: ", data.(map[string]interface{})["error"])
		return errors.New(data.(map[string]interface{})["error"].(string))
	}
	return nil
}

func (s *serviceImplpetstorePetStoreServiceserver) StoreUsers(cReq PetStoreService_StoreUsersServer) error {

	methodName := "StoreUsers"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["strmReq"] = cReq

	_, data, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
		return err
	}

	if data != nil && data.(map[string]interface{})["error"] != nil {
		log.Println("error from end server: ", data.(map[string]interface{})["error"])
		return errors.New(data.(map[string]interface{})["error"].(string))
	}
	return nil
}

func (s *serviceImplpetstorePetStoreServiceserver) BulkUsers(bdReq PetStoreService_BulkUsersServer) error {

	methodName := "BulkUsers"

	grpcData := make(map[string]interface{})
	grpcData["methodName"] = methodName
	grpcData["strmReq"] = bdReq

	_, data, err := s.trigger.CallHandler(grpcData)

	if err != nil {
		log.Println("error: ", err)
		return err
	}

	if data != nil && data.(map[string]interface{})["error"] != nil {
		log.Println("error from end server: ", data.(map[string]interface{})["error"])
		return errors.New(data.(map[string]interface{})["error"].(string))
	}
	return nil
}

func (s *serviceImplpetstorePetStoreServiceserver) ServiceInfo() *servInfo.ServiceInfo {
	return s.serviceInfo
}

